### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by Ediceu** [dotnet/docs.pt-br#99] opened 2018-12-05 18:18 UTC
Olá, teria como tropicalizar os códigos podendo ser mostrados em idiomas especificos ex:
retorno em Português(PT-BR),

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 8b2cb61f-1605-70ba-c5fb-cc4a9d9f2c8d
* Version Independent ID: 6eaec3e9-0ed9-f3ec-7516-032d57246715
* Content: [Erro do Compilador CS0103](https://docs.microsoft.com/pt-br/dotnet/csharp/language-reference/compiler-messages/cs0103)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0103.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/language-reference/compiler-messages/cs0103.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment] 2018-12-05 21:04
Issue moved to [dotnet/docs #9427](https://github.com/dotnet/docs/issues/9427) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment] 2018-12-05 21:12
Olá, @Ediceu  

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/dotnet/docs/issues/9427. 

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by mairaw** [comment] 2018-12-05 21:34
@CeciAc na realidade o comentário é um pedido para localizar o código fonte também, o que não seria um problema na documentação original. Que eu saiba images e códigos exemplos não são localizados.

/cc @JasonCard

**Comment by JasonCard** [comment] 2018-12-05 22:03
@Ediceu @mairaw @CeciAc I used Bing Translator and I'm not sure if I completely understood the issue, but I can confirm that we do not localize images and code samples, including comments within code.

**Comment by mairaw** [comment] 2018-12-05 22:04
Correct @JasonCard. I think this issue can be closed as by design. But the proper response should be told to the customer. Saying this is an issue with the original docs is not correct.

**Comment by Ediceu** [comment] 2018-12-05 22:04
Hello,

the error messages are returned from the English language compiler.

I would like to know if it is possible to tropicalize the messages to another language, for example pt-BR.

Thank you!

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by JasonCard** [comment] 2018-12-05 22:14
@mairaw Can you please help to answer latest question from @Ediceu?

**Comment by Ediceu** [comment] 2018-12-05 22:20
Example:

System.CodeDom.Compiler.CompilerParameters<http://System.CodeDom.Compiler.CompilerParameters> parameters = new CompilerParameters();
parameters.GenerateExecutable<http://parameters.GenerateExecutable> = true;
parameters.OutputAssembly<http://parameters.OutputAssembly> = Output;
CompilerResults results = icc.CompileAssemblyFromSource<http://icc.CompileAssemblyFromSource>(parameters,SourceString);



if ( results.Errors.Count<http://results.Errors.Count> > 0)
{
foreach(CompilerError CompErr in results.Errors<http://results.Errors>)
{
textBox2.Text<http://textBox2.Text> = textBox2.Text<http://textBox2.Text> +
"Line number " + CompErr.Line<http://CompErr.Line> +
", Error Number: " + CompErr.ErrorNumber<http://CompErr.ErrorNumber> +
", '" + CompErr.ErrorText<http://CompErr.ErrorText> + ";" +
Environment.NewLine<http://Environment.NewLine> + Environment.NewLine<http://Environment.NewLine>;
}
}
CompErr.ErrorText<http://CompErr.ErrorText> is returned in English.

I would like to know if it is possible to return in another language, is there any parameter such as cultureinfo?

Thank you!


Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by mairaw** [comment] 2018-12-06 02:53
This is more of a product question, not a content issue then.

@Ediceu veja se essa thread te ajuda:
https://stackoverflow.com/questions/209133/exception-messages-in-english 
Só que ao invés de en-us, vc quer pt-br. Pelo o que eu entendo, você precisa ter o language pack desejado instalado na máquina para poder acessar a mensagem em outra língua.

**Comment by CeciAc** [comment] 2018-12-07 21:07
Hello, @edic

Please check the reply above.

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Closed by CeciAc** 2018-12-07 21:07 UTC
Labels: Product Feedback
